services:
  db.videogame-management.local:
    hostname: db.videogame-management.local
    container_name: db.videogame-management.local
    image: postgres:16-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - TZ=America/Santiago
      - PGTZ=America/Santiago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videogame_management_db
    ports:
      - '13000:5432'
    volumes:
      - db-videogame-managment:/var/lib/postgresql/data

volumes:
  db-videogame-managment:
    driver: local
